version: '3.7'

services:
  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: docker/node-app/Dockerfile
#    image: test-image:latest
    command: bash -c "npm ci && npm start"
    volumes:
      - ./node-app:/usr/src/app:cached
      - node_app_modules:/usr/src/app/node_modules
    ports:
      - "8080:8080"
    expose:
      - 8080

  php_app:
    image: php:7.3.29-apache
    container_name: php_app
    volumes:
      - ./php-app/:/var/www/html/
    ports:
      - "8081:80"
    stdin_open: true
    tty: true

volumes:
  node_app_modules:
