version: '3.7'

services:
  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: docker/node-app/Dockerfile
    command: bash -c "npm ci && npm start"
    volumes:
      - ./node-app:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    expose:
      - 8080
