version: '3.7'

services:
  node_app:
    container_name: node_app
    image: test-image:latest
    command: bash -c "npm ci && npm start"
    volumes:
      - ./node-app:/usr/src/app:cached
      - node_app_modules:/usr/src/app/node_modules
    ports:
      - "8060:8080"
    expose:
      - 8080
    stdin_open: true
    tty: true

  php_app:
#    build:
#      context: .
#      dockerfile: docker/php-app/Dockerfile
    image: php:7.3.29-apache
    container_name: php_app
    volumes:
      - ./php-app/:/var/www/html/
    ports:
      - "8061:80"

volumes:
  node_app_modules:
