version: '3.7'

services:
  node_app:
    container_name: node_app
    image: test-image:latest
    command: bash -c "npm ci && npm start"
    volumes:
      - ./node-app:/usr/src/app:cached
      - node_app_modules:/usr/src/app/node_modules
    depends_on:
      - php_app
    ports:
      - "8060:8080"
    expose:
      - 8080
    stdin_open: true
    tty: true
    networks:
      - workshop-network

  php_app:
    build:
      context: .
      dockerfile: docker/php-app/Dockerfile
    container_name: php_app
    volumes:
      - ./php-app/:/var/www/html/
    ports:
      - "8061:80"
    networks:
      - workshop-network

volumes:
  node_app_modules:

networks:
  workshop-network:
    external: false
    name: workshop-network
