# set base image
FROM node:12

# set environment variable
ENV MY_WORK_DIR /usr/src/app

# execute command in container
RUN mkdir -p /usr/src/app/node_modules

# set working directory
WORKDIR $MY_WORK_DIR

# set executable for container
#CMD npm ci

